name: Android CI

on:
  push:
    branches:
      - main
    tags:        
      - v*
  pull_request:
    branches:
      - main


jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: unit test
        run: ./gradlew testReleaseUnitTest

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build with gradle
      run: ./gradlew bundleDebug

