name: assembleRelease

on:
  workflow_call:
    inputs:
      versionCode:
        required: true
        type: string
      versionName:
        required: true
        type: string
      repoName:
        required: true
        type: string

jobs:
  assembleRelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: set versionCode and versionName
        run: |
          echo "VERSION_CODE=${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "VERSION_NAME=${{ inputs.versionName }}.${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ inputs.repoName }}" >> $GITHUB_ENV

      - name: set version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.VERSION_NAME }}

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: rename artifact
        run: |
          # Rename "app-release-x.x.xxx.apk" to "$REPO_NAME-release-x.x.xxx.apk".
          artifact=(./app/build/outputs/apk/release/*.apk)
          dir_name="$(dirname $artifact)"
          file_name="$(basename $artifact)"
          new_name="${file_name/#app/$REPO_NAME}"
          mv -- "$dir_name"/{"$file_name","$new_name"}
          
          # Copy "$REPO_NAME-release-x.x.xxx.apk" to "$REPO_NAME-release-x.x.xxx-unsigned.apk".
          artifact="$dir_name/$new_name"
          ext="${artifact##*.}"
          file_name="$(basename $artifact .$ext)"
          new_name="${file_name}-unsigned.$ext"
          cp -- "$artifact" "./$new_name"

      - name: upload unsigned artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./*.apk
          retention-days: 1

      - name: sign
        uses: ilharp/sign-android-release@v1
        id: sign
        with:
          releaseDir: ./app/build/outputs/apk/release/
          signingKey: ${{ secrets.SIGNING_KEY_RELEASE }}
          keyAlias: ${{ secrets.ALIAS_RELEASE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_RELEASE }}
          keyPassword: ${{ secrets.KEY_PASSWORD_RELEASE }}
          buildToolsVersion: 33.0.1

      - name: upload signed artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ${{ steps.sign.outputs.signedFile }}
          retention-days: 1
