name: assembleRelease

on:
  workflow_call:
    inputs:
      versionCode:
        required: true
        type: string
      versionName:
        required: true
        type: string
      repoName:
        required: true
        type: string

jobs:
  assembleRelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: set versionCode and versionName
        run: |
          echo "VERSION_CODE=${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "VERSION_NAME=${{ inputs.versionName }}.${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ inputs.repoName }}" >> $GITHUB_ENV

      - name: set version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.VERSION_NAME }}

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      # "app-release-unsigned.apk" -> "$REPO_NAME-${{ env.VERSION_NAME }}-release-unsigned.apk"
      - name: rename unsigned artifact
        id: rename_unsigned
        run: |
          full_path=(./app/build/outputs/apk/release/*.apk)
          dir_name="$(dirname $full_path)"
          file_name="$(basename $full_path)"
          artifact="$dir_name/${file_name/#app/$REPO_NAME-${{ env.VERSION_NAME }}}"
          mv -- "$full_path" "$artifact"

          echo "ARTIFACT=$artifact" >> $GITHUB_OUTPUT

      - name: upload signed artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}_${{ env.VERSION_NAME }}
          path: ${{ steps.rename_unsigned.outputs.ARTIFACT }}
          retention-days: 1

      # "$REPO_NAME-${{ env.VERSION_NAME }}-release-unsigned.apk" ->
      # "$REPO_NAME-${{ env.VERSION_NAME }}-release.apk"
      - name: remove "-unsigned"
        run: |
          src_file_name=(./app/build/outputs/apk/release/*.apk)
          dest_file_name=$(echo "$src_file_name" | sed -e 's/-unsigned//g')
          mv "$src_file_name" "$dest_file_name"

      - name: sign
        uses: ilharp/sign-android-release@v1
        id: sign
        with:
          releaseDir: ./app/build/outputs/apk/release/
          signingKey: ${{ secrets.SIGNING_KEY_RELEASE }}
          keyAlias: ${{ secrets.ALIAS_RELEASE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_RELEASE }}
          keyPassword: ${{ secrets.KEY_PASSWORD_RELEASE }}
          buildToolsVersion: 33.0.1

      # "$REPO_NAME-${{ env.VERSION_NAME }}-release-signed.apk" ->
      # "$REPO_NAME-${{ env.VERSION_NAME }}-release.apk"
      - name: rename signed artifact
        id: rename_signed
        run: |
          signed_file=${{ steps.sign.outputs.signedFile }}
          artifact=$(echo "$signed_file" | sed -e 's/-signed//g')
          mv -- "$signed_file" "$artifact"

          echo "ARTIFACT=$artifact" >> $GITHUB_OUTPUT

      - name: upload signed artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}_${{ env.VERSION_NAME }}
          path: ${{ steps.rename_signed.outputs.ARTIFACT }}
          retention-days: 1
