name: connectedAndroidTest

on:
  workflow_call:

jobs:
  connectedAndroidTest:
    runs-on: macos-latest
    strategy:
      matrix:
        buildVariants: [connectedDebugAndroidTest]
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      # https://github.com/ReactiveCircus/android-emulator-runner
      - name: connectedDebugAndroidTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: |
            chmod +x gradlew
            ./gradlew ${{ matrix.buildVariants }}
