name: unitTest

on:
  workflow_call:

jobs:
  unitTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildVariants: [testDebugUnitTest, testReleaseUnitTest]
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      - name: unitTest
        run: |
          chmod +x gradlew
          ./gradlew ${{ matrix.buildVariants }}
